author: vvakame
startDay: Saturday # Friday is end of work day!

startDate: "2024-12-14T00:00:00.000+09:00"
endDate: "2024-12-27T23:59:59.999+09:00"

ignoreOrganizations:
  - TechBooster
  - techbookfest
