author: vvakame
startDay: Saturday # Friday is end of work day!

# startDate: "2021-12-18T00:00:00.000+09:00"
# endDate: "2021-12-24T23:59:59.999+09:00"

ignoreOrganizations:
  - TechBooster
  - techbookfest
